### ISSUE TITLE
Provide a front page to list containers marked as "public"

### ISSUE THREAD

**Issue by itzg** [itzg/minecraft-container-yard#13]
This was spun out of a comment on #9 .

**Comment by danpolanco** [comment]
I'll add this to my ui / frontend to-dos.

**Comment by itzg** [comment]
and I'll coordinate backend changes to track as a label and convey back to the UI via the `ContainerSummary` of  `GET /api/containers`

**Comment by danpolanco** [comment]
To summarize what we spoke about on Gitter:

Right now, we are working at the solar system level. For example, if you create your own Carina account and deploy MCCY to a cluster on that account, you have created your own solar system. You can then create worlds (i.e. containers) in that solar system that can be public or private.

This issue #13 states that we want people who go to said cluster (e.g. http://mccy.itzg.me) to be able to see the public container / worlds. Those who login at will be able to see all the worlds.

I have to think now how we want to break up the three views: public; public + private; and public + private + administration.

**Comment by danpolanco** [comment]
Ok. Given that this is at the solar system level, I think it'd work to have something like the following:

![screen shot 2016-01-10 at 4 59 54 pm](https://cloud.githubusercontent.com/assets/3826143/12224978/28f32496-b7bc-11e5-9972-6ca168d12985.png)

The landing page would then be at the galaxy level. I think this will work since it's KISS.

**Comment by itzg** [comment]
And landing page version 1 would allow UFOs (Unauthenticated uses) to see only worlds that were declared public in that solar system.

**Comment by danpolanco** [comment]
I like @itzg idea of using carousel to switch between public list and login form. Default would be it starts with the public list.

**Comment by danpolanco** [comment]
I'm working on this in a new [branch](/itzg/minecraft-container-yard/tree/feature/frontend/public/games). Right now, I have something just slapped together. I'm not sure if it works yet and it doesn't look nice yet.

**Comment by danpolanco** [comment]
Hm. It looks like I broke something when I tried to merge master into my branch. Careful. I'm going to rm the branch and then push it again.

**Comment by itzg** [comment]
No problem. I hadn't pulled the branch yet.

**Comment by danpolanco** [comment]
Ok. What I have now sort of works. On my local machine without docker containers the login screen / public game list flashes.

When you get the chance, could you update feature/public branch?
