### ISSUE TITLE
Add Spigot support

### ISSUE THREAD

**Issue by itzg** [itzg/minecraft-container-yard#17]
as a follow on to https://github.com/itzg/dockerfiles/pull/52

Needs to include both the type choice and plugin support...with some stretching of the term "mod" to keep the UI free of "mod/plugin" wording perhaps.

**Comment by sshipway** [comment]
In a way, I like that bukkit uses 'plugin' and forge uses 'mod'.  It ensures that they are kept separately and cannot interfere with each other.  If you put a mod in the plugins dir or vice-versa it causes error messages

**Comment by itzg** [comment]
True and they're quite different in that Bukkit pluigns tend not require any special client installation at all. I'll probably have them be managed and selected in the same spots in the UI, but had already carved out distinction for FML mods in the backend.

**Comment by itzg** [comment]
Now deployed to http://mccy-staging.itzg.me:8080/ for testing
