### ISSUE TITLE
Need to make it more obvious EULA needs to be accepted

### ISSUE THREAD

**Issue by itzg** [itzg/minecraft-container-yard#21]
Right now it's just another checkbox:

![image](https://cloud.githubusercontent.com/assets/988985/12079643/4a05f19c-b206-11e5-9a07-c757aaab53ca.png)

**Comment by sshipway** [comment]
Just disable the "Create it" button until the box is checked.

**Comment by itzg** [comment]
I'm already doing that, but wondering if users could be left wondering why. Perhaps I'll see if I can at least get a tooltip to show up while the button is disabled.

**Comment by itzg** [comment]
...so I'm thinking:
- Tooltip
- Bold the text...maybe
- Put a slight space above it, separating it visually from the others

**Comment by danpolanco** [comment]
I wish we had a lawyer! Preferably, they would only accept the EULA when they change versions of MC. 

Other options:
- checkbox required to login into mccy
- first time setup requires EULA acceptance and digital "signature"

I mean, we really can't determine who is accepting the EULA anyway right? There isn't any way to confirm identities online that is ubiquitous. My preference would be they just have to accept it to download a specific image.

At any rate, I think the current method works just find and I'll incorporate @itzg's suggestions while working on the new frontend.

**Comment by sshipway** [comment]
If you have the system support separate user accounts, then you could have a 'accept EULA' at first login and remember it thereafter against the individual user's profile.  Unauthenticated/public users would need to check it every time, of course.

Then you can also have authentication optionally linked to github/facebook/google/ldap/whatever , and set specific access roles against individual accounts (readonly, manage own containers only, full admin)

However in the meantime I would agree that the current method is perfectly fine :)

I think I need to add this auth stuff as a separate issue

**Comment by itzg** [comment]
All great ideas. We'll expand upon the EULA tracking when #29 is in place.

**Comment by itzg** [comment]
(Copied from gitter) 
I was thinking another quick win would be to store their answer in local storage by introducing a local storage module like this and then not pose the question when present. Even in multi-user that'll be just as convenient, closer to when they're creating the first container, and closes the gap when people share the login

**Comment by danpolanco** [comment]
I tried setting up mouse hover detection on the "Create It!" button but if a button is disabled, it can not signal mouse events, or really anything at all.

I've considered putting an overlay over the button, but I feel that's a bit hokey. I'm going to try something else that should be a good challenge for me.

I'm going to create a popup that has the "I accept the Mojang EULA" checkbox in it. It will popup when you press the button.
