### ISSUE TITLE
Need better visual feedback when container/mod views are waiting for initial content

### ISSUE THREAD

**Issue by itzg** [itzg/minecraft-container-yard#27]
While we're at it, make sure you can't see the `{{v.label}}` Angular expressions as the outer `index.ftl` is still initializing.

**Comment by itzg** [comment]
It looks like [ng-cloak](https://code.angularjs.org/1.4.8/docs/api/ng/directive/ngCloak) is actually what'll do the trick to "hide" the Angular expressions during loading.

**Comment by sshipway** [comment]
Yes, I can see the new container being started up in the mccy logs, but the web UI is completely silent... some sort of progress indicator would be a good idea.

**Comment by itzg** [comment]
In the spirit of getting 0.1 "done", let's bump this out to 0.2. Carving out the initial WebSocket support will be easy, but not trivial.

**Comment by itzg** [comment]
@sshipway the fix for #26 has been deployed to [mccy-staging](https://mccy-staging.itzg.me) and that now provides progress updates if new image layers are being pulled.

**Comment by itzg** [comment]
...otherwise, `ng-cloak` was already applied to the public container listing and it seems to be doing its job there. Other parts of the UI don't seem to show the `{{...}}` placeholders any more, but will keep an eye out for now.

**Comment by itzg** [comment]
This has been working well on [staging](https://mccy-staging.itzg.me/)
