### ISSUE TITLE
Support unix: URLs for docker socket as well as http/https

### ISSUE THREAD

**Issue by sshipway** [itzg/minecraft-container-yard#31]
This would allow the use of 

```
-v /var/run/docker.sock:/var/run/docker.sock ...  --mccy.docker-host-uri=unix:///var/run/docker.sock 
```

when starting the container, which removes the need to expose your Docker API to a TCP port that may be accessed from somewhere else.

**Comment by itzg** [comment]
Awesome, the Spotify library does also support [UNIX sockets](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/UnixConnectionSocketFactory.java). In fact, the example you show with a `unix://` URI should work already.

**Comment by sshipway** [comment]
I've already tried, and the code denies anything not starting "http".  I think this is your code, though:

```
default message [The DOCKER_HOST URI must be HTTP or HTTPS]
```

**Comment by itzg** [comment]
Doh, it is my code applying a regex to the config field. That's easy to fix :)
