### ISSUE TITLE
Minecraft connect string should obtain IP from API, not from docker API URL.

### ISSUE THREAD

**Issue by sshipway** [itzg/minecraft-container-yard#35]
If using the unix:// API URL, then the connect string for minecraft reported in the "Current Containers" uses 'localhost'.  Instead, it should use the API to query the exposed IP of the container (IP of parent Docker host) and use this, or possibly allow this string to be globally configurable.

For compatibility with docker clusters, and in situations whereservice is proxied or port-forwarded, and this IP might be different for different containers, or even different from the host IP.

**Comment by itzg** [comment]
I'll investigate some more, but from initial glance at the code, I attempt to pull it from the reported port mapping from the `docker ps` equivalent call; however, if it's reported as `0.0.0.0` I'm currently falling back to the "address" derived from `dockerHostUri`...which is not very useful in `unix://` mode.

At a minimum I'll improve the fallback logic to allow for an ultimate override to definitively declare the "connect using" address.
