### ISSUE TITLE
"Download client side mods" link is incorrect

### ISSUE THREAD

**Issue by sshipway** [itzg/minecraft-container-yard#49]
The URL of the MCCY server is https://mccy.itzg.me/ ; however, the link of the "Download client side mods" points to http://mccy-staging.itzg.me:8080/

I suspect that the HTTP headers are not being checked for creating the self-referential URL and this is the hostname/port behind the load balancer/proxy?

**Comment by itzg** [comment]
Yeah, I naively wrote that code in the pre-proxy days :) I'll look at this one while I also figure out nginx upload issues.

**Comment by itzg** [comment]
It turns out this is due to some of the containers being created before the proxy was in place. So those URLs were computed with old "8080" type address.
- [x] Purge the old test containers on primary cluster (AFTER rolling #48 to production)
