### ISSUE TITLE
"This deployment" footer is rendering wrong

### ISSUE THREAD

**Issue by itzg** [itzg/minecraft-container-yard#50]
...but I might need to change configuration with the new theme.

![image](https://cloud.githubusercontent.com/assets/988985/12467481/4e48fa58-bfa1-11e5-830b-975ec2ff1891.png)

**Comment by danpolanco** [comment]
I noticed that as well. Something I should look into?

**Comment by danpolanco** [comment]
Perhaps I changed the #if statements incorrectly.

**Comment by itzg** [comment]
I think I found the cause. My config in the `docker-compose.yml` is still

```
    --mccy.deployment-powered-by.image-src=images/powered-by/powered-by-carina-wide.png 
```

but the images path is now `img/`. That would great if you could fix the compose file.
