### ISSUE TITLE
Need to start bumping up the version since we show it now in the footer

### ISSUE THREAD

**Issue by itzg** [itzg/minecraft-container-yard#54]
![image](https://cloud.githubusercontent.com/assets/988985/12467492/638c73f4-bfa1-11e5-93eb-08c57a6178ee.png)

**Comment by danpolanco** [comment]
We should be able to use ftl, yeah? :smiley:

**Comment by itzg** [comment]
Yep and I believe Maven embeds a version into the jar that can feed into the ftl.

**Comment by danpolanco** [comment]
yay! :dancer:

**Comment by itzg** [comment]
The version footer shows more detail as Maven properties `build.branch` and `build.job` are set:

![image](https://cloud.githubusercontent.com/assets/988985/12538807/15afbffa-c2a9-11e5-8551-fa62dfc3598f.png)
