### ISSUE TITLE
Better feedback when login fails

### ISSUE THREAD

**Issue by danpolanco** [itzg/minecraft-container-yard#60]
The login page doesn't say anything when you enter the wrong password.

Perhaps a toaster? Might be ugly. Perhaps a little popup below or slide out below.

**Comment by itzg** [comment]
We're using toasters elsewhere for success/error, but that wouldn't look right for the login page. 

I would agree with a panel above or below the credentials fields.

**Comment by itzg** [comment]
1. You may have noticed by the URL query part is populated with `?error` on failed login
2. I'd suggest extending the "white area" of the login panel with the failure notice

![container yard - login - google chrome_001](https://cloud.githubusercontent.com/assets/988985/12534284/a646a9ea-c216-11e5-8f0b-7aa68435acd5.png)
