### ISSUE TITLE
Add logout action

### ISSUE THREAD

**Issue by itzg** [itzg/minecraft-container-yard#67]
Triggered by `POST /logout`

![image](https://cloud.githubusercontent.com/assets/988985/12699489/88fade76-c782-11e5-8bb5-be6df6cde153.png)

**Comment by danpolanco** [comment]
Definitely should be done before 0.1.

**Comment by itzg** [comment]
You may have already spotted it, but [fa-sign-out](http://fortawesome.github.io/Font-Awesome/icon/sign-out/) will be a perfect icon for this one.

**Comment by danpolanco** [comment]
I put a little button at the top right as a step toward implementing:

![screen shot 2016-01-31 at 9 52 54 pm](https://cloud.githubusercontent.com/assets/3826143/12709054/03139bb6-c865-11e5-9877-3179680d6581.png)

If you don't like it, let me know :)
