### ISSUE TITLE
When removing a container, confirmation dialog falls under header

### ISSUE THREAD

**Issue by itzg** [itzg/minecraft-container-yard#71]
![image](https://cloud.githubusercontent.com/assets/988985/12704723/56ef78e8-c826-11e5-80ac-49c8ddde36f6.png)

**Comment by danpolanco** [comment]
I believe adding:

``` sass
  .modal {
    top: 10%;
  }
```

To theme.scss -> theme will fix it.

![screen shot 2016-01-31 at 9 29 38 pm](https://cloud.githubusercontent.com/assets/3826143/12708844/def20658-c861-11e5-8d41-a6b4842c0dc3.png)

**Comment by itzg** [comment]
Cool, I was hoping just a CSS offset tweak would do it.
