### ISSUE TITLE
Expired sessions should return to login page

### ISSUE THREAD

**Issue by sshipway** [itzg/minecraft-container-yard#79]
When a session expires, it behaves oddly - displaying some containers, not showing modules, etc.  Instead, it should redirect back to the top (login) screen.

**Comment by itzg** [comment]
That used to work correctly, but I haven't paid attention in a while...so I'm glad you pointed this out.

**Comment by sshipway** [comment]
I am testing via the https://mccy.itzg.me/ test server, so this may be behind revision (0.1-175)

**Comment by itzg** [comment]
With session timeout turned way down I can re-create it on my local environment. Now I'm trying to figure out why some XHR actions trigger the login redirect and some don't.

For example, clicking "Reload" doesn't behave right, but going to "Manage Mods" does redirect properly.

**Comment by itzg** [comment]
Oh, I know what it is: it's because some of the API calls, like `GET /containers`, are now allowed for both authenticated and unauthenticated users so public containers can be obtained. Now I can think of ways to tighten that back up.

**Comment by itzg** [comment]
Fixed by e5c1ef7ea45ef04789c9371d91208c751a347ef0
