### ISSUE TITLE
Apply the 'name' as the initial MOTD and normalize into legal container name

### ISSUE THREAD

**Issue by itzg** [itzg/minecraft-container-yard#8]
...otherwise the allowed characters for the name is limited to identifier characters

**Comment by sshipway** [comment]
Maybe the default MOTD could be something like "A Minecraft server running ${name}"

The original name should probably be stored in a container label, such as mccy.name, for later reference (labels are useful)

**Comment by itzg** [comment]
Just a remind to document the label at https://github.com/itzg/minecraft-container-yard/wiki/Container-labels

**Comment by itzg** [comment]
#40 took care of most of this. Let's open a new issue for MOTD aspects.
